//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class path {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal path() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("project.Plugins.path", typeof(path).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseReader plugin completed successfully..
        /// </summary>
        internal static string complete_succesfuly {
            get {
                return ResourceManager.GetString("complete succesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseReader plugin completed unsuccessfully..
        /// </summary>
        internal static string complete_unsuccesfuly {
            get {
                return ResourceManager.GetString("complete unsuccesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty command.
        /// </summary>
        internal static string DatabasePlugin_Makequery_empty_command {
            get {
                return ResourceManager.GetString("DatabasePlugin_Makequery_empty_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is empty.
        /// </summary>
        internal static string empty_table {
            get {
                return ResourceManager.GetString("empty table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running databaseReader plugin....
        /// </summary>
        internal static string running_database_plugin {
            get {
                return ResourceManager.GetString("running_database_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Host=localhost;Port=5432;Username=postgres;Password=admin;Database=project&quot;.
        /// </summary>
        internal static string uploadconnection {
            get {
                return ResourceManager.GetString("uploadconnection", resourceCulture);
            }
        }
    }
}
